# Generated by Django 5.0.7 on 2024-07-24 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="jobName",
            new_name="jobNumber",
        ),
    ]
