# Generated by Django 5.0.7 on 2024-07-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_rename_jobname_customuser_jobnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveddatasetsfromuser",
            name="description",
            field=models.TextField(default="无", verbose_name="文件描述"),
        ),
    ]
