# Generated by Django 5.0.7 on 2024-07-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_saveddatasetsfromuser_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saveddatasetsfromuser",
            name="file_path",
            field=models.CharField(default="", max_length=255, verbose_name="文件存放路径"),
        ),
    ]
